<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{d11ea297-e766-42ef-a2af-be53d91dcc2d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counterA:INT;
	counter2:INT;
	useless_variable:BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counterA:=counterA+1;
counter2:=counter2+1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="13" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>