<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{d11ea297-e766-42ef-a2af-be53d91dcc2d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	counter:INT;
	counter2:INT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[counter:=counter+1;
counter2:=counter2+1;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>